export const DEFAULT_INDICATORS = {
  primary_industry: 'Technology',
  log_market_cap: 20.5,
  log_employees: 8.1,
  log_revenue_wins: 15.2,
  log_scope_1: 4.5,
  log_scope_2: 3.2,
  log_scope_3: 5.1,
  log_energy_consumption: 6.8,
  log_waste_production: 3.4,
  log_water_consumption: 7.2,
  log_hours_of_training_wins: 5.0,
  log_ceo_compensation: 14.5,
  independent_board_members_percentage: 65.0,
  log_legal_costs_paid_for_controversies: 0.0,
  intensity_scope_1: 0.5,
  intensity_scope_2: 0.3,
  intensity_scope_3: 1.2,
  intensity_energy: 0.8,
  intensity_waste: 0.1,
  intensity_water: 0.9,
  intensity_training: 0.4,
  intensity_productivity: 1.5,
  revenue_negative_flag: 0,
};

export type ESGIndicators = typeof DEFAULT_INDICATORS;

export const INDICATOR_CATEGORIES = {
  Environmental: [
    'log_scope_1',
    'log_scope_2',
    'log_scope_3',
    'log_energy_consumption',
    'log_waste_production',
    'log_water_consumption',
    'intensity_scope_1',
    'intensity_scope_2',
    'intensity_scope_3',
    'intensity_energy',
    'intensity_waste',
    'intensity_water',
  ],
  Social: [
    'log_hours_of_training_wins',
    'log_ceo_compensation',
    'intensity_training',
    'intensity_productivity',
  ],
  Governance: [
    'independent_board_members_percentage',
    'log_legal_costs_paid_for_controversies',
    'revenue_negative_flag',
  ],
  General: [
    'primary_industry',
    'log_market_cap',
    'log_employees',
    'log_revenue_wins',
  ],
};

export const INDICATOR_LABELS: Record<string, string> = {
  primary_industry: 'Secteur d\'activité',
  log_market_cap: 'Valeur boursière de l\'entreprise',
  log_employees: 'Nombre total d\'employés',
  log_revenue_wins: 'Chiffre d\'affaires annuel',
  log_scope_1: 'Émissions CO₂ directes (usines, véhicules)',
  log_scope_2: 'Émissions CO₂ liées à l\'électricité achetée',
  log_scope_3: 'Émissions CO₂ de toute la chaîne (fournisseurs…)',
  log_energy_consumption: 'Consommation d\'énergie totale',
  log_waste_production: 'Déchets produits',
  log_water_consumption: 'Eau consommée',
  log_hours_of_training_wins: 'Heures de formation des employés',
  log_ceo_compensation: 'Rémunération annuelle du PDG',
  independent_board_members_percentage: '% d\'administrateurs indépendants au conseil',
  log_legal_costs_paid_for_controversies: 'Montant des litiges et amendes payés',
  intensity_scope_1: 'CO₂ direct rapporté au chiffre d\'affaires',
  intensity_scope_2: 'CO₂ électricité rapporté au chiffre d\'affaires',
  intensity_scope_3: 'CO₂ chaîne rapporté au chiffre d\'affaires',
  intensity_energy: 'Énergie consommée par € de chiffre d\'affaires',
  intensity_waste: 'Déchets produits par € de chiffre d\'affaires',
  intensity_water: 'Eau consommée par € de chiffre d\'affaires',
  intensity_training: 'Formation par € de chiffre d\'affaires',
  intensity_productivity: 'Chiffre d\'affaires généré par employé',
  revenue_negative_flag: 'Revenus en baisse cette année ? (0 = Non, 1 = Oui)',
};
