export const DEFAULT_INDICATORS = {
  primary_industry: 'Technology',
  log_market_cap: 20.5,
  log_employees: 8.1,
  log_revenue_wins: 15.2,
  log_scope_1: 4.5,
  log_scope_2: 3.2,
  log_scope_3: 5.1,
  log_energy_consumption: 6.8,
  log_waste_production: 3.4,
  log_water_consumption: 7.2,
  log_hours_of_training_wins: 5.0,
  log_ceo_compensation: 14.5,
  independent_board_members_percentage: 65.0,
  log_legal_costs_paid_for_controversies: 0.0,
  intensity_scope_1: 0.5,
  intensity_scope_2: 0.3,
  intensity_scope_3: 1.2,
  intensity_energy: 0.8,
  intensity_waste: 0.1,
  intensity_water: 0.9,
  intensity_training: 0.4,
  intensity_productivity: 1.5,
  revenue_negative_flag: 0,
};

export type ESGIndicators = typeof DEFAULT_INDICATORS;

export const INDICATOR_CATEGORIES = {
  Environmental: [
    'log_scope_1',
    'log_scope_2',
    'log_scope_3',
    'log_energy_consumption',
    'log_waste_production',
    'log_water_consumption',
    'intensity_scope_1',
    'intensity_scope_2',
    'intensity_scope_3',
    'intensity_energy',
    'intensity_waste',
    'intensity_water',
  ],
  Social: [
    'log_hours_of_training_wins',
    'log_ceo_compensation',
    'intensity_training',
    'intensity_productivity',
  ],
  Governance: [
    'independent_board_members_percentage',
    'log_legal_costs_paid_for_controversies',
    'revenue_negative_flag',
  ],
  General: [
    'primary_industry',
    'log_market_cap',
    'log_employees',
    'log_revenue_wins',
  ],
};

export const INDICATOR_LABELS: Record<string, string> = {
  primary_industry: 'Secteur principal',
  log_market_cap: 'Log Market Cap',
  log_employees: 'Log Nombre d\'employés',
  log_revenue_wins: 'Log Revenu (wins)',
  log_scope_1: 'Log Scope 1 (directes)',
  log_scope_2: 'Log Scope 2 (indirectes)',
  log_scope_3: 'Log Scope 3 (chaîne)',
  log_energy_consumption: 'Log Consommation énergie',
  log_waste_production: 'Log Production déchet',
  log_water_consumption: 'Log Consommation eau',
  log_hours_of_training_wins: 'Log Heures de formation',
  log_ceo_compensation: 'Log Compensation CEO',
  independent_board_members_percentage: '% Membres indépendants',
  log_legal_costs_paid_for_controversies: 'Log Coûts légaux',
  intensity_scope_1: 'Intensité Scope 1',
  intensity_scope_2: 'Intensité Scope 2',
  intensity_scope_3: 'Intensité Scope 3',
  intensity_energy: 'Intensité énergie',
  intensity_waste: 'Intensité déchet',
  intensity_water: 'Intensité eau',
  intensity_training: 'Intensité formation',
  intensity_productivity: 'Intensité productivité',
  revenue_negative_flag: 'Flag revenu négatif',
};
